services:
  django-app:
    build:
      context: ./django_project
      dockerfile: Dockerfile
    env_file:
      - .env
      - ./django_project/.env
    container_name: django-app
    command: ["./wait-for-it.sh", "mysql-db:3306", "-t", "60", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./django_project:/app
    depends_on:
      - mysql-db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://django-app:8000
    env_file:
      - ./frontend/.env
    depends_on:
      - django-app

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: capstone_db
      MYSQL_USER: capstone_user
      MYSQL_PASSWORD: securepassword123
      MYSQL_ROOT_PASSWORD: s8812371i
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:
